---
name: CI
on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
  - cron: 0 0 * * *
<<<<<<< HEAD
permissions:
  contents: read
=======
>>>>>>> 2e1af6a196322ff27de854b562e170662232f025
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version:
        - '3.1'
        - '3.3'
<<<<<<< HEAD
        test-suite:
        - vmdb
        - security
=======
>>>>>>> 2e1af6a196322ff27de854b562e170662232f025
    services:
      postgres:
        image: manageiq/postgresql:13
        env:
          POSTGRESQL_USER: root
          POSTGRESQL_PASSWORD: smartvm
          POSTGRESQL_DATABASE: vmdb_test
        options: "--health-cmd pg_isready --health-interval 2s --health-timeout 5s
          --health-retries 5"
        ports:
        - 5432:5432
    env:
<<<<<<< HEAD
      TEST_SUITE: "${{ matrix.test-suite }}"
=======
      BUNDLE_WITH: qpid_proton
>>>>>>> 2e1af6a196322ff27de854b562e170662232f025
      PGHOST: localhost
      PGPASSWORD: smartvm
      CC_TEST_REPORTER_ID: "${{ secrets.CC_TEST_REPORTER_ID }}"
    steps:
    - uses: actions/checkout@v4
    - name: Set up system
      run: bin/before_install
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "${{ matrix.ruby-version }}"
        bundler-cache: true
      timeout-minutes: 30
    - name: Prepare tests
      run: bin/setup
<<<<<<< HEAD
    - name: Check DB access on initialization
      run: bundle exec rake test:verify_no_db_access_loading_rails_environment
    - name: Run tests
      run: bundle exec rake
    - name: Report code coverage
      if: ${{ github.ref == 'refs/heads/master' && matrix.ruby-version == '3.3' && matrix.test-suite == 'vmdb' }}
      continue-on-error: true
      uses: paambaati/codeclimate-action@v5
=======
    - name: Run tests
      run: bundle exec rake
    - name: Report code coverage
      if: ${{ github.ref == 'refs/heads/master' && matrix.ruby-version == '3.3' }}
      continue-on-error: true
      uses: paambaati/codeclimate-action@v9
>>>>>>> 2e1af6a196322ff27de854b562e170662232f025
